
const metrics = 
    [
        {   "id":"1", //provisional
            "firstName":"Pura Vida",
            "lastName":"Premium",
            "email":"puravidaviajespremium@gmail.com",
            "telephone":"54",
            "isBlocked":false,
            "userStatus":"Administrador",
            "metrics" : [
                {'Prospecto' : '0'},
                {'Contactada' : '0'},
                {'En espera' : '0'},
                {'Ganada' : '0'},
                {'Perdido' : '0'},
            ]
        },
        {   "id":"2",
            "firstName":"Sergio Dario",
            "lastName":"Aguilar",
            "email":"sergiodarioaguilar2017@gmail.com",
            "telephone":"543487227400",
            "isBlocked":false,
            "userStatus":"Colaborador",
            "metrics" : [
                {'Prospecto' : '2'},
                {'Contactada' : '18'},
                {'En espera' : '4'},
                {'Ganada' : '12'},
                {'Perdido' : '2'},
            ]
        },
        {   "id":"3",
            "firstName":"Jhonatan",
            "lastName":"Escorihuela",
            "email":"jhonattan1410@gmail.com",
            "telephone":"5",
            "isBlocked":false,
            "userStatus":"Colaborador",
            "metrics" : [
                {'Prospecto' : '5'},
                {'Contactada' : '14'},
                {'En espera' : '4'},
                {'Ganada' : '8'},
                {'Perdido' : '2'},
            ]
        },
        {   "id":"4",
            "firstName":"Melodi",
            "lastName":"Balossino",
            "email":"melodibalossino@gmail.com",
            "telephone":"5",
            "isBlocked":false,
            "userStatus":"Colaborador",
            "metrics" : [
                {'Prospecto' : '6'},
                {'Contactada' : '14'},
                {'En espera' : '2'},
                {'Ganada' : '10'},
                {'Perdido' : '2'},
            ]
        },
        {   "id":"5",
            "firstName":"Keny",
            "lastName":"Espinoza",
            "email":"kespinozaluis@gmail.com",
            "telephone":"5",
            "isBlocked":false,
            "userStatus":"Colaborador",
            "metrics" : [
                {'Prospecto' : '7'},
                {'Contactada' : '15'},
                {'En espera' : '6'},
                {'Ganada' : '8'},
                {'Perdido' : '1'},
            ]
        },
        {   "id":"6",
            "firstName":"Camila",
            "lastName":"Castro",
            "email":"camicastro.11.94@gmail.com",
            "telephone":"5",
            "isBlocked":false,
            "userStatus":"Colaborador",
            "metrics" : [
                {'Prospecto' : '1'},
                {'Contactada' : '15'},
                {'En espera' : '9'},
                {'Ganada' : '5'},
                {'Perdido' : '1'},
            ]
        },
        {   "id":"7",
            "firstName":"Gustavo",
            "lastName":"Aguilar",
            "email":"gustavoaguilar911@gmail.com",
            "telephone":"54",
            "isBlocked":false,
            "userStatus":"Administrador",
            "metrics" : [
                {'Prospecto' : '0'},
                {'Contactada' : '0'},
                {'En espera' : '0'},
                {'Ganada' : '0'},
                {'Perdido' : '0'},
            ]
        },
        {   "id":"8",
            "firstName":"Cande",
            "lastName":"yarossi",
            "email":"cyarossi@soyhenry.com",
            "telephone":"54",
            "isBlocked":false,
            "userStatus":"Administrador",
            "metrics" : [
                {'Prospecto' : '9'},
                {'Contactada' : '17'},
                {'En espera' : '5'},
                {'Ganada' : '10'},
                {'Perdido' : '2'},
            ]
        },
        {   "id":"9",
            "firstName":"Fabian",
            "lastName":"Ramirez",
            "email":"fabioerv_1994@hotmail.com",
            "telephone":"5",
            "isBlocked":false,
            "userStatus":"Colaborador",
            "metrics" : [
                {'Prospecto' : '7'},
                {'Contactada' : '16'},
                {'En espera' : '2'},
                {'Ganada' : '8'},
                {'Perdido' : '6'},
            ]
        },
        {   "id":"10",
            "firstName":"Julian",
            "lastName":"Castaño",
            "email":"juliancaristizabal@gmail.com",
            "telephone":"5",
            "isBlocked":false,
            "userStatus":"Colaborador",
            "metrics" : [
                {'Prospecto' : '2'},
                {'Contactada' : '14'},
                {'En espera' : '1'},
                {'Ganada' : '12'},
                {'Perdido' : '1'},
            ]
        },
        {   "id":"11",
            "firstName":"Alan",
            "lastName":"Martinez",
            "email":"rodrigoalanmartinez@gmail.com",
            "telephone":"5",
            "isBlocked":false,
            "userStatus":"Colaborador",
            "metrics" : [
                {'Prospecto' : '2'},
                {'Contactada' : '12'},
                {'En espera' : '2'},
                {'Ganada' : '4'},
                {'Perdido' : '6'},
            ]
        }
    ]


export default metrics;